spring.application.name=EmployeeMangement

spring.datasource.url=jdbc:postgresql://localhost:5432/emanagement
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show.sql=true


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.security.user.name=Arpit
spring.security.user.password=A@123

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

server.port=8081