spring.application.name=EmployeeMangement

spring.datasource.url=jdbc:postgresql://localhost:5432/emanagement
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show.sql=true


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.security.user.name=Arpit
spring.security.user.password=A@123

spring.security.oauth2.client.registration.google.client-id=
Spring.security.auth2.client.registration.google.client-secret=